name: Trigger auto deployment for jdk11-m-plain

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/jdk11-m-plain-AutoDeployTrigger-a2e33956-531f-4c57-93ec-dd01df2db7a0.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.JDK11MPLAIN_REGISTRY_USERNAME }}
          password: ${{ secrets.JDK11MPLAIN_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: anishi/jdk11-m-plain:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.JDK11MPLAIN_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n jdk11-m-plain -g ACA --server docker.io --username  ${{ secrets.JDK11MPLAIN_REGISTRY_USERNAME }} --password ${{ secrets.JDK11MPLAIN_REGISTRY_PASSWORD }}
            az containerapp update -n jdk11-m-plain -g ACA --image anishi/jdk11-m-plain:${{ github.sha }}
